//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bermuda.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BmdCurrent
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string BriefText { get; set; }
        public Nullable<long> CmntCount { get; set; }
        public Nullable<long> StarCount { get; set; }
        public Nullable<long> PraiseCount { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
