//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bermuda.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BmdDbEntities : DbContext
    {
        public BmdDbEntities()
            : base("name=BmdDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BmdConsignee> BmdConsignees { get; set; }
        public virtual DbSet<BmdCurrent> BmdCurrents { get; set; }
        public virtual DbSet<BmdCurrentCmnt> BmdCurrentCmnts { get; set; }
        public virtual DbSet<BmdCurrentCmntPraise> BmdCurrentCmntPraises { get; set; }
        public virtual DbSet<BmdCurrentCmntReply> BmdCurrentCmntReplies { get; set; }
        public virtual DbSet<BmdCurrentCmntReplyPraise> BmdCurrentCmntReplyPraises { get; set; }
        public virtual DbSet<BmdCurrentPraise> BmdCurrentPraises { get; set; }
        public virtual DbSet<BmdCurrentStar> BmdCurrentStars { get; set; }
        public virtual DbSet<BmdNotice> BmdNotices { get; set; }
        public virtual DbSet<BmdNoticeCmnt> BmdNoticeCmnts { get; set; }
        public virtual DbSet<BmdNoticeCmntReply> BmdNoticeCmntReplies { get; set; }
        public virtual DbSet<BmdNoticeSpecie> BmdNoticeSpecies { get; set; }
        public virtual DbSet<BmdNoticeTrace> BmdNoticeTraces { get; set; }
        public virtual DbSet<BmdOrder> BmdOrders { get; set; }
        public virtual DbSet<BmdOrderItem> BmdOrderItems { get; set; }
        public virtual DbSet<BmdProduct> BmdProducts { get; set; }
        public virtual DbSet<BmdRoot> BmdRoots { get; set; }
        public virtual DbSet<BmdShoppingCart> BmdShoppingCarts { get; set; }
        public virtual DbSet<BmdTopic> BmdTopics { get; set; }
        public virtual DbSet<BmdTopicJoin> BmdTopicJoins { get; set; }
        public virtual DbSet<BmdUser> BmdUsers { get; set; }
        public virtual DbSet<BmdUserFollow> BmdUserFollows { get; set; }
    }
}
