//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bermuda.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BmdDbEntities : DbContext
    {
        public BmdDbEntities()
            : base("name=BmdDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BmdConsignee> BmdConsignees { get; set; }
        public virtual DbSet<BmdCurrent> BmdCurrents { get; set; }
        public virtual DbSet<BmdCurrentCmnt> BmdCurrentCmnts { get; set; }
        public virtual DbSet<BmdCurrentCmntPraise> BmdCurrentCmntPraises { get; set; }
        public virtual DbSet<BmdCurrentCmntReply> BmdCurrentCmntReplies { get; set; }
        public virtual DbSet<BmdCurrentCmntReplyPraise> BmdCurrentCmntReplyPraises { get; set; }
        public virtual DbSet<BmdCurrentPraise> BmdCurrentPraises { get; set; }
        public virtual DbSet<BmdCurrentStar> BmdCurrentStars { get; set; }
        public virtual DbSet<BmdNotice> BmdNotices { get; set; }
        public virtual DbSet<BmdNoticeCmnt> BmdNoticeCmnts { get; set; }
        public virtual DbSet<BmdNoticeCmntReply> BmdNoticeCmntReplies { get; set; }
        public virtual DbSet<BmdNoticeSpecie> BmdNoticeSpecies { get; set; }
        public virtual DbSet<BmdNoticeTrace> BmdNoticeTraces { get; set; }
        public virtual DbSet<BmdOrder> BmdOrders { get; set; }
        public virtual DbSet<BmdOrderItem> BmdOrderItems { get; set; }
        public virtual DbSet<BmdProduct> BmdProducts { get; set; }
        public virtual DbSet<BmdRoot> BmdRoots { get; set; }
        public virtual DbSet<BmdShoppingCart> BmdShoppingCarts { get; set; }
        public virtual DbSet<BmdTopic> BmdTopics { get; set; }
        public virtual DbSet<BmdTopicJoin> BmdTopicJoins { get; set; }
        public virtual DbSet<BmdUser> BmdUsers { get; set; }
        public virtual DbSet<BmdUserFollow> BmdUserFollows { get; set; }
    
        public virtual int JoinTopicsProc(Nullable<long> user_id, string title, string text, string brief_text, Nullable<long> topic1_id, Nullable<long> topic2_id, Nullable<long> topic3_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(long));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            var brief_textParameter = brief_text != null ?
                new ObjectParameter("brief_text", brief_text) :
                new ObjectParameter("brief_text", typeof(string));
    
            var topic1_idParameter = topic1_id.HasValue ?
                new ObjectParameter("topic1_id", topic1_id) :
                new ObjectParameter("topic1_id", typeof(long));
    
            var topic2_idParameter = topic2_id.HasValue ?
                new ObjectParameter("topic2_id", topic2_id) :
                new ObjectParameter("topic2_id", typeof(long));
    
            var topic3_idParameter = topic3_id.HasValue ?
                new ObjectParameter("topic3_id", topic3_id) :
                new ObjectParameter("topic3_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("JoinTopicsProc", user_idParameter, titleParameter, textParameter, brief_textParameter, topic1_idParameter, topic2_idParameter, topic3_idParameter);
        }
    }
}
