//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bermuda.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BmdOrder
    {
        public long Id { get; set; }
        public Nullable<long> BuyerId { get; set; }
        public Nullable<long> SellerId { get; set; }
        public Nullable<long> ConsigneeId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    }
}
