//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bermuda.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BmdProduct
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public string Tag { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Inventory { get; set; }
        public string ImgUrl { get; set; }
        public string Tale { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
