//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bmd.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BmdEntities : DbContext
    {
        public BmdEntities()
            : base("name=BmdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BmdRoot> bmdRoot { get; set; }
        public virtual DbSet<BmdUser> bmdUser { get; set; }
        public virtual DbSet<Current> current { get; set; }
        public virtual DbSet<CurrentCmnt> currentCmnt { get; set; }
        public virtual DbSet<CurrentReply> currentReply { get; set; }
        public virtual DbSet<CurrentStar> currentStar { get; set; }
        public virtual DbSet<Follow> follow { get; set; }
        public virtual DbSet<Notice> notices { get; set; }
        public virtual DbSet<NoticeCmnt> noticeCmnt { get; set; }
        public virtual DbSet<NoticeReply> noticeReply { get; set; }
        public virtual DbSet<NoticeTrace> noticeTrace { get; set; }
        public virtual DbSet<Species> species { get; set; }
        public virtual DbSet<Topic> topic { get; set; }
        public virtual DbSet<TopicJoin> topicJoin { get; set; }
    }
}
