//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bmd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BmdRoot
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Permission { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Avatar { get; set; }
        public string Remark { get; set; }
    }
}
