//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bmd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> SpeciesId { get; set; }
        public string Type { get; set; }
        public string Title { get; set; }
        public string Place { get; set; }
        public string Location { get; set; }
        public string LfDate { get; set; }
        public string Img { get; set; }
        public string ContactWay { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<long> CmntCount { get; set; }
        public Nullable<long> TraceCount { get; set; }
        public string Status { get; set; }
    }
}
